apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashbake
spec:
  selector:
    matchLabels:
      app: flashbake
  replicas: 1
  template:
    metadata:
      labels:
        app: flashbake
    spec:
      containers:
      - name: flashbake
        image: flashbake:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10732
          name: client
        - containerPort: 11732
          name: baker
---
apiVersion: v1
kind: Service
metadata:
  name: flashbake
spec:
  ports:
  - port: 10732
    name: client
    targetPort: 10732
  - port: 11732
    name: baker
    targetPort: 11732
  selector:
    app: flashbake
